export const readingCards = [
  {
    id: 'hello-everyone',
    english: 'Hello everyone!',
    chinese: '大家好！',
    phrases: ['Hello everyone!'],
  },
  {
    id: 'my-name',
    english: 'My name is Sherry.',
    chinese: '我的名字叫 Sherry。',
    phrases: ['My name is', 'Sherry.'],
  },
  {
    id: 'eight-years-old',
    english: 'I am eight years old.',
    chinese: '我八岁了。',
    phrases: ['I am', 'eight years old.'],
  },
  {
    id: 'sing-and-draw',
    english: 'I can sing English songs and draw nice pictures.',
    chinese: '我会唱英文歌，也会画漂亮的图画。',
    phrases: ['I can', 'sing English songs', 'and draw nice pictures.'],
  },
  {
    id: 'english-stories',
    english: 'I like reading fun English stories.',
    chinese: '我喜欢读有趣的英文故事。',
    phrases: ['I like', 'reading fun English stories.'],
  },
  {
    id: 'lovely-cat',
    english: 'I’ve got a lovely cat at home.',
    chinese: '我家里有一只可爱的小猫。',
    phrases: ['I’ve got', 'a lovely cat', 'at home.'],
  },
  {
    id: 'pink-dress',
    english: 'I am wearing a pink dress today.',
    chinese: '我今天穿着一条粉色连衣裙。',
    phrases: ['I am wearing', 'a pink dress', 'today.'],
  },
  {
    id: 'talking-happily',
    english: 'I am standing and talking with you happily now.',
    chinese: '我现在正开心地站在这里和大家说话。',
    phrases: ['I am standing', 'and talking with you', 'happily now.'],
  },
  {
    id: 'love-family',
    english: 'I love my family; my parents always play with me.',
    chinese: '我爱我的家人；我的爸爸妈妈总是和我一起玩。',
    phrases: ['I love my family;', 'my parents always', 'play with me.'],
  },
  {
    id: 'favourites',
    english: 'My favourite fruit is apple and my favourite colour is purple.',
    chinese: '我最喜欢的水果是苹果，最喜欢的颜色是紫色。',
    phrases: ['My favourite fruit', 'is apple', 'and my favourite colour', 'is purple.'],
  },
  {
    id: 'competition',
    english: 'I’m glad to join the competition. Thank you!',
    chinese: '我很高兴参加这次比赛。谢谢大家！',
    phrases: ['I’m glad', 'to join the competition.', 'Thank you!'],
  },
];

export const wordDefinitions = {
  a: '一个；一只',
  always: '总是',
  am: '是',
  and: '和；并且',
  apple: '苹果',
  at: '在',
  can: '能够；会',
  cat: '猫',
  colour: '颜色',
  competition: '比赛',
  draw: '画画',
  dress: '连衣裙',
  eight: '八',
  english: '英语；英文的',
  everyone: '每个人；大家',
  family: '家人；家庭',
  favourite: '最喜欢的',
  fruit: '水果',
  fun: '有趣的',
  glad: '高兴的',
  got: '有',
  happily: '开心地',
  hello: '你好',
  home: '家',
  i: '我',
  "i'm": '我是',
  "i've": '我已经；我有',
  is: '是',
  join: '参加；加入',
  like: '喜欢',
  lovely: '可爱的',
  love: '爱；喜爱',
  me: '我',
  my: '我的',
  name: '名字',
  nice: '漂亮的；好的',
  now: '现在',
  old: '岁的；老的',
  parents: '父母',
  pictures: '图画；图片',
  pink: '粉色的',
  play: '玩',
  purple: '紫色的',
  reading: '阅读',
  sherry: 'Sherry（人名）',
  sing: '唱歌',
  songs: '歌曲',
  standing: '站立',
  stories: '故事',
  talking: '说话；交谈',
  thank: '谢谢',
  the: '这个；那个',
  to: '去；向；到',
  today: '今天',
  wearing: '穿着',
  with: '和……一起',
  years: '年；岁',
  you: '你；你们',
};
